### ISSUE TITLE
Non reproductible

### ISSUE THREAD

**Issue by begarco** [begarco/SpectralClustering#2]
@theCmaker j'ai effectué les changements qu'on avait fait ensemble le problème c'est que des fois l'algo marche bien et des fois il donne une image complètement noire alors que j'utilise exactement la même commande :
```
./spectral_clustering convexe.bmp 2 25
```
Je comprends pas trop d'où ça peut venir étant donné que le résultat change et qu'il ne devrait rien y avoir d'aléatoire, peut être une fuite quelque part.

**Comment by begarco** [comment]
Je pense avoir réglé le problème j'ai supprimé des erreurs mémoires avec valgrind. Tu me diras si ça te donne une image noire en résultat des fois. On a de bon résultats avec le cercle aussi.
Faudra qu'on se choisisse un pool d'image pour faire les tests, trouver les bons sigma et remplir le rapport.

**Comment by theCmaker** [comment]
Ah super ! Je vais faire des tests, je te confirme ça bientôt
